### ISSUE TITLE
Config parameters that have defaults should be optional

### ISSUE THREAD

**Issue by hrj** [librecaptcha/lc-core#105]
When a config parameter has a default value, the user should be able to optionally omit it from the config file.

For example, since `playgroundEnabled` has a default value of true, the user need not specify it.

Currently, the server throws an exception for missing parameters.

**Comment by rr83019** [comment]
Here's a list of config parameters, please choose the ones we want to make optional:

- [ ] port
- [ ] address
- [ ] throttle
- [ ] seed
- [ ] captchaExpiryLimit
- [ ] threadDelay
- [ ] playgroundEnabled
- [ ] corsHeader
- [ ] maxAttempts

**Comment by hrj** [comment]
Looks like all of them can be optional, and have sane defaults 😄

**Comment by rr83019** [comment]
Cool, any suggestion on what the defaults should be?

**Comment by hrj** [comment]
The defaults can be what is inside the automatically created config file:

```
{
  "randomSeed" : some random integer,
  "port" : 8888,
  "address" : "0.0.0.0",
  "captchaExpiryTimeLimit" : 5,
  "throttle" : 1000,
  "threadDelay" : 2,
  "playgroundEnabled" : true,
  "corsHeader" : "",
  "maxAttempts" : 10,
}
```

**Comment by rr83019** [comment]
Making the `playgroundEnabled` field string from bool. 

The `extract` function of json4s is not able to convert `JBool` to `java.lang.String`

**Comment by hrj** [comment]
Ideally, we shouldn't change the type because it will break existing configurations.

I have added a suggestion to the PR, please have a look.
