### ISSUE TITLE
Standardise Image Captcha sizes

### ISSUE THREAD

**Issue by rr83019** [librecaptcha/lc-core#24]
Have a standard size or dimension for various captchas.
Dimensions can be based on the type of captcha

**Comment by hrj** [comment]
@rr83019 Can you do a quick study of image sizes offered by other captcha providers. We can then finalise the sizes that lc-core will provide.

**Comment by hrj** [comment]
Closing as dup of #98 (although this is the older issue, the newer one has more activity).
