### ISSUE TITLE
Performance Benchmark

### ISSUE THREAD

**Issue by rr83019** [librecaptcha/lc-core#39]
Test the performance of various parameters of the existing system.

**Comment by rr83019** [comment]
Will be using [locust](https://docs.locust.io/en/stable/index.html#) for load testing.

**Comment by hrj** [comment]
Looks good. You could simulate a swarm of users that:
1. Get a captcha challenge
2. Submit a solution for it after 5 to 10 seconds

Let's see how many concurrent uses can do that.

**Comment by rr83019** [comment]
### Load test data for 1000 concurrent users spawning at a rate of 10 users/second.

Statistics for the test
![Stats-1000-10](https://user-images.githubusercontent.com/20319757/86124718-32324600-baf9-11ea-82f7-18f570c56963.png)

Total requests per second
![Total-request-per-second-1000-10](https://user-images.githubusercontent.com/20319757/86125985-319aaf00-bafb-11ea-9708-65b0a99246f4.png)

Response times
![Response-times-1000-10](https://user-images.githubusercontent.com/20319757/86126011-3c554400-bafb-11ea-8dcb-9e5ee4d10988.png)

Number of users
![Number-of-users-1000-10](https://user-images.githubusercontent.com/20319757/86126031-44ad7f00-bafb-11ea-94df-c0e5cf052cca.png)

**Comment by rr83019** [comment]
### Load test data for 1000 concurrent users spawning at a rate of 100 users/second.

Statistics for the test
![Stats-1000-100](https://user-images.githubusercontent.com/20319757/86126210-95bd7300-bafb-11ea-9030-ff6f23e7ed0b.png)

Total requests per second
![Total-requests-per-second-1000-100](https://user-images.githubusercontent.com/20319757/86126263-a53cbc00-bafb-11ea-850f-49c01da5d0a8.png)

Response times
![Response-times-1000-100](https://user-images.githubusercontent.com/20319757/86126282-ac63ca00-bafb-11ea-8793-78cfb619d3c1.png)

Number of users
![Number-of-users-1000-100](https://user-images.githubusercontent.com/20319757/86126298-b2f24180-bafb-11ea-9255-a0ad3bf9620f.png)

Failures 
![Failures-1000-100](https://user-images.githubusercontent.com/20319757/86126362-cef5e300-bafb-11ea-9f94-34418c7f803d.png)

**Comment by rr83019** [comment]
### Load test data for 2000 concurrent users spawning at a rate of 10 users/second.

Statistics for the test 
![Stats-2000-10](https://user-images.githubusercontent.com/20319757/86126468-02387200-bafc-11ea-9e1e-008794ccc4ce.png)

Total requests per second
![Total-requests-per-second-2000-10](https://user-images.githubusercontent.com/20319757/86126430-f3ea5600-bafb-11ea-8d08-ccfb144800d8.png)

Response times
![Response-times-2000-10](https://user-images.githubusercontent.com/20319757/86126487-09f81680-bafc-11ea-8311-1bd2723262dc.png)

Number of users
![Number-of-users-2000-10](https://user-images.githubusercontent.com/20319757/86126503-0fedf780-bafc-11ea-8383-20ac96ad1cb8.png)

Failures
![Failures-2000-10](https://user-images.githubusercontent.com/20319757/86126515-15e3d880-bafc-11ea-91d1-ad60e1f8e45a.png)

**Comment by rr83019** [comment]
I also observed this unusual spike in failures for a few Milliseconds when the test starts.
![Failure-anamoly](https://user-images.githubusercontent.com/20319757/86126723-707d3480-bafc-11ea-9ad1-afebd34621c3.png)
From 17:34:15 to 17:34:30

**Comment by hrj** [comment]
This is great! Tons of things to analyse.

* Can you upload the test script to gist.github.com?
* Let's fix on `1000 concurrent users @ 100 users/second` for now. 
* We need to ensure that each test begins with a clean and consistent state. For example, by removing the database, and populating it fresh every time. Can you write a script for the test? It should roughly do the following:

```
rm << captcha database files >>
sbt runMain << classNameForPopulatingDB >>
run locust
```

* Before we analyse the performance, we need to address the failures. For the most common failure, can you raise a separate issue in this repo, with the stack trace and other details included?

**Comment by rr83019** [comment]
### Load test data for 1000 concurrent users spawning at a rate of 10 users/second after DB upgrade and DB sync

Statistics for the test 
![Stats-1000-10-new](https://user-images.githubusercontent.com/20319757/86609427-8cd01400-bfc9-11ea-977c-63bf24870b81.png)

Total requests per second
![Total-requests-per-second-1000-10-new](https://user-images.githubusercontent.com/20319757/86609478-9bb6c680-bfc9-11ea-96f3-9b275a7b5f5a.png)

Response times
![Response-times-1000-10-new](https://user-images.githubusercontent.com/20319757/86609556-b2f5b400-bfc9-11ea-985e-8f88b704fff8.png)

Number of users
![Number-of-users-1000-10-new](https://user-images.githubusercontent.com/20319757/86609590-be48df80-bfc9-11ea-9aa6-e947e81607a4.png)

Failures
![Failures-1000-10-new](https://user-images.githubusercontent.com/20319757/86609631-cc96fb80-bfc9-11ea-9779-81bda08cba4c.png)

**Comment by rr83019** [comment]
### Load test data for 1000 concurrent users spawning at a rate of 100 users/second after DB upgrade and DB sync

Statistics for the test
![Stats-1000-100-new](https://user-images.githubusercontent.com/20319757/86609713-f51ef580-bfc9-11ea-98c9-239e06639da5.png)

Total requests per second
![Total-reqest-per-second-1000-100-new](https://user-images.githubusercontent.com/20319757/86609734-fe0fc700-bfc9-11ea-8930-a5721bd39615.png)

Response times
![Response-times-1000-100-new](https://user-images.githubusercontent.com/20319757/86609758-06680200-bfca-11ea-99e4-a304d90026b9.png)

Number of users
![Number-of-users-1000-100-new](https://user-images.githubusercontent.com/20319757/86609782-108a0080-bfca-11ea-9680-f1e5ce49aaaf.png)

Failures
![Failures-1000-100-new](https://user-images.githubusercontent.com/20319757/86609812-17b10e80-bfca-11ea-8e41-ca2211c26138.png)


Note: The majority of failures on `/captcha` endpoint are because of the rate limiter. It gives back a 400 error when the limit is reached, as seen in failures.

**Comment by hrj** [comment]
## Performance results for CRUD app

### Config
* OpenJDK 11
* locust 100 users (each user contributes about 310 requests per second)
* Each locust user calls create then increment : read is in the ratio 1 : 8
* Xodus 1.3.232
* h2-1.4.200.jar
* Locust and LC-core running on the same DO droplet

### RPS
For Xodus, peak RPS is 2150
For H2, peak RPS is 2400

Response times were sub 1ms for both

**Comment by hrj** [comment]
After multiple tests, we decided to retain H2 as the database, and added some tweaks to the schema.
