### ISSUE TITLE
GC of solved captchas

### ISSUE THREAD

**Issue by hrj** [librecaptcha/lc-core#50]
* Change `solved` column to an integer that counts number of times the captcha was solved
* After every N captchas are created, delete the captchas that have been solved more than M times.
* After every N*10 captchas are created, delete the captchas that have been solved more than M/2 times
* Don't serve captchas that have been solved more than M/2 times

N and M need to be configurable, but for now, we can hard-code them to 1000 and 10 respectively.

**Comment by rr83019** [comment]
- Add a timestamp column to the captcha map table
- Update the timestamp with the current time whenever a captcha is served
- Increment M when a captcha is solved 
- While selecting a new captcha to be served, the `solved` count should be less than M
- For GC the `solved` count should be more than M and the last served time should be less than the current time - time to solve captcha
- For the `answer` endpoint, it should accept the solution only if the last served time is less than the current time - time to solve
- When the time to solve exceeds or incase of a captcha is garbage collected it should return an error status and ask to request for a new captcha

**Comment by hrj** [comment]
Closed via #52
