### ISSUE TITLE
Check licenses of dependencies

### ISSUE THREAD

**Issue by hrj** [librecaptcha/lc-core#66]
The `JLHTTP` library being used currently is GPL licensed. Let's try to find a replacement for it.

Also need to check other dependencies!

**Comment by rr83019** [comment]
Replacing `JLHTTP` with [Fibry](https://github.com/lucav76/Fibry) which is under MIT License 
[json4s](https://github.com/json4s/json4shttps://github.com/json4s/json4s) is under Apache 2.0 License
[scrimage](https://github.com/sksamuel/scrimage) is under Apache 2.0 LicenseApache 2.0 License

**Comment by hrj** [comment]
> Replacing `JLHTTP` with [Fibry](https://github.com/lucav76/Fibry) which is under MIT License
> [json4s](https://github.com/json4s/json4shttps://github.com/json4s/json4s) is under Apache 2.0 License
> [scrimage](https://github.com/sksamuel/scrimage) is under Apache 2.0 License

Excellent! It would be good to check licenses recursively for transitive dependencies, using something like this plugin: https://github.com/sbt/sbt-license-report

But that doesn't seem to be maintained :(

**Comment by hrj** [comment]
This article might be useful: https://www.devwithimagination.com/2020/05/17/license-and-version-checks-the-manual-way-maven/

**Comment by rr83019** [comment]
Found a python package we can look into: https://github.com/nexB/scancode-toolkit

**Comment by rr83019** [comment]
# librecaptcha-licenses

Category | License | Dependency | Notes
--- | --- | --- | ---
Apache | [Apache License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0.txt) | com.github.zh79325 # open-gif # 1.0.4 | <notextile></notextile>
Apache | [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0.txt) | commons-io # commons-io # 2.6 | <notextile></notextile>
Apache | [Apache-2.0](http://www.apache.org/licenses/LICENSE-2.0) | org.json4s # json4s-ast_2.13 # 3.6.11 | <notextile></notextile>
Apache | [Apache-2.0](http://www.apache.org/licenses/LICENSE-2.0) | org.json4s # json4s-core_2.13 # 3.6.11 | <notextile></notextile>
Apache | [Apache-2.0](http://www.apache.org/licenses/LICENSE-2.0) | org.json4s # json4s-jackson_2.13 # 3.6.11 | <notextile></notextile>
Apache | [Apache-2.0](http://www.apache.org/licenses/LICENSE-2.0) | org.json4s # json4s-scalap_2.13 # 3.6.11 | <notextile></notextile>
Apache | [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0) | org.scala-lang # scala-library # 2.13.5 | <notextile></notextile>
Apache | [The Apache 2.0 License](https://opensource.org/licenses/Apache-2.0) | com.sksamuel.scrimage # scrimage-core # 4.0.12 | <notextile></notextile>
Apache | [The Apache 2.0 License](https://opensource.org/licenses/Apache-2.0) | com.sksamuel.scrimage # scrimage-filters # 4.0.12 | <notextile></notextile>
Apache | [The Apache Software License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0.txt) | ar.com.hjg # pngj # 2.1.0 | <notextile></notextile>
Apache | [The Apache Software License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0.txt) | com.drewnoakes # metadata-extractor # 2.14.0 | <notextile></notextile>
Apache | [The Apache Software License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0.txt) | com.fasterxml.jackson.core # jackson-annotations # 2.9.10 | <notextile></notextile>
Apache | [The Apache Software License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0.txt) | com.fasterxml.jackson.core # jackson-core # 2.9.10 | <notextile></notextile>
Apache | [The Apache Software License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0.txt) | com.fasterxml.jackson.core # jackson-databind # 2.9.10.8 | <notextile></notextile>
BSD | [BSD](LICENSE.txt) | com.thoughtworks.paranamer # paranamer # 2.8 | <notextile></notextile>
BSD | [The BSD License](http://www.adobe.com/devnet/xmp/library/eula-xmp-library-java.html) | com.adobe.xmp # xmpcore # 6.0.6 | <notextile></notextile>
BSD | [The BSD License](https://github.com/haraldk/TwelveMonkeys#license) | com.twelvemonkeys.common # common-image # 3.6 | <notextile></notextile>
BSD | [The BSD License](https://github.com/haraldk/TwelveMonkeys#license) | com.twelvemonkeys.common # common-io # 3.6 | <notextile></notextile>
BSD | [The BSD License](https://github.com/haraldk/TwelveMonkeys#license) | com.twelvemonkeys.common # common-lang # 3.6 | <notextile></notextile>
BSD | [The BSD License](https://github.com/haraldk/TwelveMonkeys#license) | com.twelvemonkeys.imageio # imageio-core # 3.6 | <notextile></notextile>
BSD | [The BSD License](https://github.com/haraldk/TwelveMonkeys#license) | com.twelvemonkeys.imageio # imageio-jpeg # 3.6 | <notextile></notextile>
BSD | [The BSD License](https://github.com/haraldk/TwelveMonkeys#license) | com.twelvemonkeys.imageio # imageio-metadata # 3.6 | <notextile></notextile>
LGPL | [GNU Lesser General Public License](http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html) | ch.qos.logback # logback-classic # 1.1.2 | <notextile></notextile>
LGPL | [GNU Lesser General Public License](http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html) | ch.qos.logback # logback-core # 1.1.2 | <notextile></notextile>
MIT | [MIT License](http://www.opensource.org/licenses/mit-license.php) | org.slf4j # slf4j-api # 1.7.7 | <notextile></notextile>


Report by [sbt-license-report](https://github.com/sbt/sbt-license-report)

**Comment by hrj** [comment]
@rr83019 Excellent. All licenses look fine for our purposes.

Would have been good to integrate the plugin into our build / CI, but it doesn't seem very stable / maintained. Closing this issue for now.

**Comment by rr83019** [comment]
We can probably use some other libraries that have docker support to integrate it into the CI pipeline. 
E.g here: http://www.lib4dev.in/info/pivotal/LicenseFinder/1262785
