### ISSUE TITLE
Config option to specify maxAttempts for a CAPTCHA

### ISSUE THREAD

**Issue by hrj** [librecaptcha/lc-core#80]
It is currently hardcoded in `statements.scala` to a value of 10.

**Comment by kringo** [comment]
I get False right after entering answer wrong 1st time, followed by Expired when entering the correct answer the 2nd time.

In other words, if got wrong the first time it doesn't allow / give a chance to re-enter correct value.

**Comment by hrj** [comment]
@kringo Are you re-attempting with the same token? That will always fail, otherwise bots will get multiple chances to try different guesses for the same token. After a failed attempt you need to ask the API for a fresh CAPTCHA challenge.

The way this works is:
The server maintains a set of CAPTCHA challenges. When a new captcha is requested from the API, it creates a UUID for the challenge that can only be attempted once. After an attempt is made for that UUID, that UUID is deleted, and internally an attempt count is incremented for the CAPTCHA.

When a CAPTCHA has been attempted many times (according to the internal counter), that CAPTCHA is retired, and a new CAPTCHA is generated to replace it.

This issues is about making the internal threshold configurable.

**Comment by rr83019** [comment]
Should I take this up?

**Comment by hrj** [comment]
@rr83019 Yeah sure, and welcome back :)
