### ISSUE TITLE
Create one text distorted captcha

### ISSUE THREAD

**Issue by hrj** [librecaptcha/lc-core#9]
As discussed, this captcha will use multiple fonts, multiple colors, random rotation and random spacing.

It should accept a folder as input, which contains 3 sub folders: `easy`, `medium`, `hard` which contain fonts of corresponding complexity.

**Comment by hrj** [comment]
Added first cut in https://github.com/librecaptcha/lc-core/pull/14/files
:+1: 

Now you need to make the fonts dynamic, by loading them from a directory.

**Comment by PrajwalGoudar** [comment]
Check the new PR and let me know if it solves this issue.
