### ISSUE TITLE
Hello world style example?

### ISSUE THREAD

**Issue by jave** [librecaptcha/lc-core#95]
Hello,

It would be nice with a hello world style example.

I'm looking at create a small captcha enabled application, probably in Clojure.

I couldnt find any hello world style examples to get me started.

/Joakim

**Comment by hrj** [comment]
Hi,

You mean an example for using the API? I agree, we missed that.

In the meanwhile, you can have a look at the JS code in the demo here:
https://github.com/librecaptcha/lc-core/blob/master/src/main/resources/index.html

I will try to put a more succinct version in the README.

**Comment by hrj** [comment]
As reference, I have added a JS code sample in the README:
https://github.com/librecaptcha/lc-core#example-usage

If you get it working in clojure, please add an example in the Wiki, or paste it here.
